-- Fix: SOPs readable without waiting for auth session
drop policy if exists "sops_read" on public.sops;
create policy "sops_read" on public.sops for select using (true);

insert into public.sops (slug,title,pillar,pillar_color,category,read_time_mins,is_popular,tier_required,summary,content) values
('three-layer-bottleneck-model','Three-Layer Bottleneck Model','Sales & Conversion','#1D9E75','Frameworks',8,true,'free','Every problem maps to Surface System or Foundation. Most operators fix the wrong layer.','# Three-Layer Bottleneck Model' || chr(10) || 'Layer 1 Surface - the visible symptom. Layer 2 System - the broken process. Layer 3 Foundation - the belief making the process failure inevitable. Durable fixes happen at Layer 3.'),
('five-pillar-growth-framework','Five-Pillar Growth Infrastructure Framework','Market & Offer Clarity','#6D4AE6','Frameworks',12,true,'free','How the five pillars connect causally.','# Five-Pillar Framework' || chr(10) || 'Pillar 1 Market and Offer Clarity. Pillar 2 Customer Acquisition. Pillar 3 Sales and Conversion. Pillar 4 Profit Optimization. Pillar 5 Financial Control. Most upstream weak pillar is the highest-leverage fix.'),
('outbound-sales-playbook','Outbound Sales Playbook','Customer Acquisition','#378ADD','Playbooks',25,true,'operator','A complete outbound system from ICP to booked call.','# Outbound Sales Playbook' || chr(10) || 'Prerequisite: Pillar 1 score above 3.0. Phase 1 define ICP precisely. Phase 2 build message with observation offer proof and question. Phase 3 five-touch sequence over 21 days. Phase 4 track CAC per channel weekly.'),
('90-day-growth-sprint-playbook','90-Day Growth Sprint Playbook','Sales & Conversion','#1D9E75','Playbooks',20,false,'operator','Structure a focused 90-day execution sprint around your primary bottleneck.','# 90-Day Growth Sprint' || chr(10) || 'Weeks 1 to 4 Foundation. Weeks 5 to 9 Build. Weeks 10 to 12 Optimise. Week 13 Review. One bottleneck one metric one action per week.'),
('why-most-operators-fix-wrong-thing','Why Most Operators Fix the Wrong Thing','Market & Offer Clarity','#6D4AE6','Learnings',5,true,'free','The most expensive mistake in business: solving symptoms instead of root causes.','# Why Most Operators Fix the Wrong Thing' || chr(10) || 'Pattern: problem appears, surface fix applied, problem returns in 90 days. Test: if this fix works, why will the problem not return in 90 days? If you cannot answer, you are fixing the wrong layer.'),
('cac-payback-explained','CAC and Payback Period','Customer Acquisition','#378ADD','Learnings',7,false,'starter','The two numbers that tell you if acquisition is working economically.','# CAC and Payback Period' || chr(10) || 'CAC = total spend divided by customers acquired per channel. Payback = CAC divided by monthly revenue per customer. Under 6 months healthy. Over 12 months unsustainable. Rank channels by CAC and invest in the lowest.');
